application: precio-energia
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /static
  static_dir: static
  
- url: /.*
  script: main.application

  
libraries:

- name: django
  version: "1.4"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'Django_AppEngine.settings'
